[[check]]
type="Exclude"
scope="all"
category="Infinite"

[[check]]
type="Exclude"
id="STAN-0101"
file="src/Acov/Report/Report.hs"

[[check]]
type="Exclude"
category="Partial"
file="src/Acov/Report/Report.hs"

[[check]]
type="Exclude"
category="Partial"
file="src/Acov/Frontend/Width.hs"



